import express from "express";
import path from "path";
import { createServer as createViteServer } from "vite";
import { GoogleGenAI } from "@google/genai";
import dotenv from "dotenv";

dotenv.config();

async function startServer() {
  const app = express();
  const PORT = 3000;

  app.use(express.json());

  // API endpoint for Gemini wishing generation
  app.post("/api/generate-blessing", async (req, res) => {
    try {
      const { senderName, recipientName, language } = req.body;
      
      const apiKey = process.env.GEMINI_API_KEY;
      if (!apiKey) {
        return res.status(500).json({ error: "GEMINI_API_KEY is not configured on the server." });
      }

      const ai = new GoogleGenAI({
        apiKey: apiKey,
        httpOptions: {
          headers: {
            'User-Agent': 'aistudio-build',
          }
        }
      });

      let prompt = "";
      if (language === "Sinhala") {
        prompt = `Write a serene, peaceful, and spiritually deep Vesak blessing wishing message in beautiful Sinhala language (සිංහල).
The sender is '${senderName || "someone special"}' wishing the recipient '${recipientName || "a dear one"}'. 
Do not include labels like sender, receiver, etc. Keep the message highly elegant, spiritual, wishing safety, health, happiness, and peace under Buddha's guidance. Maximum 2 short sentences. Let it sound authentic and poetic, with beautiful Sinhala characters.`;
      } else if (language === "Tamil") {
        prompt = `Write a serene, peaceful, and spiritually uplifting Vesak festival wishing message in beautiful Tamil language (தமிழ்).
The sender is '${senderName || "someone special"}' wishing the recipient '${recipientName || "you"}'.
Keep the message highly elegant, spiritual, wishing peaceful mind, prosperity, and blessings of Dhamma. Maximum 2 short sentences. No subject headers or labels.`;
      } else {
        prompt = `Write a serene, beautiful, and spiritually uplifting Buddhist Vesak wishing message in English. 
The sender is '${senderName || "someone special"}' and the recipient is '${recipientName || "you"}'. 
The message should be short, peaceful, filled with loving-kindness (Metta), wishing them peace, tranquility, and the blessings of the Triple Gem (Buddha, Dhamma, Sangha). Keep it to 2 elegant sentences maximum. Do not include labels like sender/receiver/subject.`;
      }

      const response = await ai.models.generateContent({
        model: "gemini-3.5-flash",
        contents: prompt,
      });

      const messageContent = response.text?.trim() || "Wishing you a peaceful and blessed Vesak!";
      // Clean leading/trailing quotes often generated by LLMs
      const cleanMessage = messageContent.replace(/^["']|["']$/g, "").trim();

      res.json({ message: cleanMessage });
    } catch (err: any) {
      console.error("Gemini API Error:", err);
      res.status(500).json({ error: err.message || "An error occurred while generating blessing." });
    }
  });

  // Serve static paths or use Vite dev server
  if (process.env.NODE_ENV !== "production") {
    const vite = await createViteServer({
      server: { middlewareMode: true },
      appType: "spa",
    });
    app.use(vite.middlewares);
  } else {
    const distPath = path.join(process.cwd(), 'dist');
    app.use(express.static(distPath));
    app.get('*', (req, res) => {
      res.sendFile(path.join(distPath, 'index.html'));
    });
  }

  app.listen(PORT, "0.0.0.0", () => {
    console.log(`Server running on port ${PORT}`);
  });
}

startServer();
